Fix build with clang on Linux
Using -stdlib=libc++ is not necessary with clang on Linux. In fact it
causes an error here on Ubuntu 20.04 with my self-installed boost 1.74.0:

/usr/local/include/boost/config/detail/select_stdlib_config.hpp:26:14: fatal error: 'cstddef' file not found
#    include <cstddef>
             ^~~~~~~~~